### ISSUE TITLE
Can't get input stream from URL 

### ISSUE THREAD

**Issue by illogicalsong** [pl3xgaming/Pl3xMap-Fabric#5]
`11:42:23.249 net.minecraft.class_2983 pool-2-thread-1 [STDERR]: Caused by: java.io.FileNotFoundException: http://mc.adhdmc.net:8089//tiles/resource/3/15_18.png 11:42:23.249 net.minecraft.class_2983 pool-2-thread-1 [STDERR]: at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1981) 11:42:23.249 net.minecraft.class_2983 pool-2-thread-1 [STDERR]: at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577) 11:42:23.249 net.minecraft.class_2983 pool-2-thread-1 [STDERR]: at java.base/java.net.URL.openStream(URL.java:1192) 11:42:23.249 net.minecraft.class_2983 pool-2-thread-1 [STDERR]: at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1405) 11:42:23.249 net.minecraft.class_2983 pool-2-thread-1 [STDERR]: ... 5 more 11:42:23.347 net.minecraft.class_2983 pool-2-thread-3 [STDERR]: javax.imageio.IIOException: Can't get input stream from URL! 11:42:23.348 net.minecraft.class_2983 pool-2-thread-3 [STDERR]: at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1407) 11:42:23.348 net.minecraft.class_2983 pool-2-thread-3 [STDERR]: at net.pl3x.map.fabric.tiles.TileQueue.run(TileQueue.java:25) 11:42:23.348 net.minecraft.class_2983 pool-2-thread-3 [STDERR]: at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) 11:42:23.348 net.minecraft.class_2983 pool-2-thread-3 [STDERR]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) 11:42:23.348 net.minecraft.class_2983 pool-2-thread-3 [STDERR]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) 11:42:23.348 net.minecraft.class_2983 pool-2-thread-3 [STDERR]: at java.base/java.lang.Thread.run(Thread.java:831)`

Seems to happen when I rtp into an area that hasn't had the map rendered yet on the server map

![image](https://user-images.githubusercontent.com/45906780/131175427-0d00ba9e-da67-4134-8f5c-2df968a55339.png)

**Comment by illogicalsong** [comment]
More info:

Does not appear to only happen in this case, is also happening now while im at my server spawn and not moving
![image](https://user-images.githubusercontent.com/45906780/131233405-25d85027-47b6-4cd8-94cb-7d48c2393639.png)
![image](https://user-images.githubusercontent.com/45906780/131233421-15ce4c9a-5919-4865-ba40-14bb4c660f37.png)
Only other thing I can think of is that I was hidden from the map when the errors started. I did /map show, and they didn't stop, but relogged while still showing, and they  did stop.

Current error log:

`16:27:46.974
net.minecraft.class_2983
pool-2-thread-6
[STDERR]: javax.imageio.IIOException: Can't get input stream from URL!
16:27:46.974
net.minecraft.class_2983
pool-2-thread-6
[STDERR]: 	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1407)
16:27:46.974
net.minecraft.class_2983
pool-2-thread-6
[STDERR]: 	at net.pl3x.map.fabric.tiles.TileQueue.run(TileQueue.java:25)
16:27:46.974
net.minecraft.class_2983
pool-2-thread-6
[STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
16:27:46.974
net.minecraft.class_2983
pool-2-thread-6
[STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
16:27:46.974
net.minecraft.class_2983
pool-2-thread-6
[STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
16:27:46.974
net.minecraft.class_2983
pool-2-thread-6
[STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:831)
16:27:46.974
net.minecraft.class_2983
pool-2-thread-6
[STDERR]: Caused by: java.io.FileNotFoundException: http://mc.adhdmc.net:8089//tiles/world/3/-1952_-1956.png
16:27:46.974
net.minecraft.class_2983
pool-2-thread-6
[STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1981)
16:27:46.974
net.minecraft.class_2983
pool-2-thread-6
[STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
16:27:46.974
net.minecraft.class_2983
pool-2-thread-6
[STDERR]: 	at java.base/java.net.URL.openStream(URL.java:1192)
16:27:46.974
net.minecraft.class_2983
pool-2-thread-6
[STDERR]: 	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1405)
16:27:46.974
net.minecraft.class_2983
pool-2-thread-6
[STDERR]: 	... 5 more`
